### ISSUE TITLE
My message is not showing

### ISSUE THREAD

**Issue by abhi99sind** [Rohitpandey357/React-chat-app#1]
I typed my message and pressed enter and nothing happens on the page. Please correct it ASAP. Your other repositories are awesome. And thanks for helping me in installing react

**Comment by Rohitpandey357** [comment]
Thanks for going through my github!
You have to create your own scaledrone channel and replace "Your Scaledrone Channel" text in app.js with your scaledrone channel in order to use the app.

**Comment by abhi99sind** [comment]
ohkk but you must specify that in the description

**Comment by Rohitpandey357** [comment]
Yeah I think so! Thanks for the suggestion.
